server:
  port: 8081


spring:
  datasource:
    username: root
    password: xxyp123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sms_sdk?characterEncoding=UTF-8
